CREATE TABLE events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    folder_path  TEXT NOT NULL
);

CREATE TABLE participants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    university  VARCHAR(255) NOT NULL,
    city        VARCHAR(255) NOT NULL,
    faculty     VARCHAR(255) NOT NULL
);

CREATE TABLE templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    file_type   VARCHAR(10) NOT NULL,
    file_path   TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE generations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT NOT NULL,
    participant_id  BIGINT NOT NULL,
    template_id     BIGINT NOT NULL,
    document_type   VARCHAR(32) NOT NULL,
    output_format   VARCHAR(8) NOT NULL,
    file_path       TEXT NOT NULL,
    status          VARCHAR(16) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE settings (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key     VARCHAR(100) NOT NULL,
    value   TEXT NOT NULL
);